import { WEEKDAYS, defaultSlotsForDay, type DietaryProfile } from "@/types/domain";
import { checkRecipeAgainstAllergies, isTreeNutsAllowed, containsTreeNuts } from "./allergy-guard";
import type { GeneratedMeal, GeneratedWeek } from "./menu-schema";

export interface WeekValidationIssue {
  code: string;
  message: string;
  day?: string;
  slot?: string;
}

export interface WeekValidationResult {
  isValid: boolean;
  issues: WeekValidationIssue[];
}

/**
 * Validazione deterministica e server-side della settimana generata, eseguita
 * SEMPRE prima del salvataggio — indipendentemente da cosa abbia proposto il
 * provider AI (mock o reale). Copre §18: presenza dei pasti attesi, assenza
 * dei pranzi feriali automatici, allergeni, ingredienti vietati, quantità,
 * unità, duplicazioni, porzioni, struttura della settimana.
 *
 * NOTA SUL CONTEGGIO DEI PASTI: il brief descrive testualmente "17 momenti
 * alimentari" ma poi elenca 5 giorni feriali × 2 pasti (colazione, cena) + 2
 * giorni di weekend × 3 pasti (colazione, pranzo, cena) = 10 + 6 = 16. La
 * somma aritmetica della struttura descritta è quindi 16, non 17: trattiamo
 * "17" come un refuso del brief e validiamo esattamente la struttura
 * enumerata (16 pasti generati automaticamente), lasciando comunque aperta
 * la possibilità di aggiungere manualmente un pranzo nei giorni feriali (che
 * non viene mai generato automaticamente).
 */
export function validateGeneratedWeek(
  week: GeneratedWeek,
  profiles: DietaryProfile[],
  memberNames?: Record<string, string>,
): WeekValidationResult {
  const issues: WeekValidationIssue[] = [];

  // 1. Struttura della settimana: weekStartDate deve essere un lunedì.
  // Nota: le date "YYYY-MM-DD" del dominio sono date pure, senza fuso
  // orario: si interpretano SEMPRE come UTC (suffisso "Z") e si leggono con
  // i metodi UTC, per non dipendere dal fuso orario del server che esegue
  // questo codice.
  const start = new Date(`${week.weekStartDate}T00:00:00Z`);
  const startWeekday = start.getUTCDay(); // 0 = domenica, 1 = lunedì
  if (startWeekday !== 1) {
    issues.push({
      code: "week_start_not_monday",
      message: "La settimana deve iniziare di lunedì.",
    });
  }

  // 2. Presenza esatta dei pasti attesi (struttura dei 16 momenti) + assenza
  //    di pranzi feriali generati automaticamente.
  const expected = new Map<string, boolean>(); // "giorno|slot" -> trovato
  for (const day of WEEKDAYS) {
    for (const slot of defaultSlotsForDay(day)) {
      expected.set(`${day}|${slot}`, false);
    }
  }

  const autoGeneratedMeals = week.meals.filter((m) => !m.isManuallyAdded);

  for (const meal of autoGeneratedMeals) {
    const key = `${meal.day}|${meal.slot}`;
    if (meal.slot === "pranzo" && meal.day !== "sabato" && meal.day !== "domenica") {
      issues.push({
        code: "weekday_lunch_auto_generated",
        message: `Il pranzo di ${meal.day} non deve essere generato automaticamente.`,
        day: meal.day,
        slot: meal.slot,
      });
      continue;
    }
    if (!expected.has(key)) {
      issues.push({
        code: "unexpected_meal_slot",
        message: `Slot pasto non atteso: ${meal.day} ${meal.slot}.`,
        day: meal.day,
        slot: meal.slot,
      });
      continue;
    }
    expected.set(key, true);
  }

  for (const [key, found] of expected.entries()) {
    if (!found) {
      const [day, slot] = key.split("|");
      issues.push({
        code: "missing_meal_slot",
        message: `Manca il pasto atteso: ${day} ${slot}.`,
        day,
        slot,
      });
    }
  }

  // 3. Allergeni: ogni pasto deve essere sicuro per tutti i membri (verifica
  //    "peggiore caso": la generazione automatica non conosce ancora chi sarà
  //    presente pasto per pasto, quindi si valida contro l'intera famiglia).
  for (const meal of week.meals) {
    const check = checkRecipeAgainstAllergies(meal.recipe, profiles, { memberNames });
    if (!check.isSafe) {
      for (const violation of check.violations) {
        issues.push({
          code: "allergen_conflict",
          message: `"${meal.recipe.name}" (${meal.day} ${meal.slot}) contiene ${violation.matchedIngredient}, incompatibile con l'allergia di ${violation.memberName} a ${violation.allergen}.`,
          day: meal.day,
          slot: meal.slot,
        });
      }
    }
  }

  // 4. Frutta secca: consentita solo se nessuno in famiglia ha allergia dichiarata.
  if (!isTreeNutsAllowed(profiles)) {
    for (const meal of week.meals) {
      if (containsTreeNuts(meal.recipe)) {
        issues.push({
          code: "tree_nuts_not_allowed",
          message: `"${meal.recipe.name}" (${meal.day} ${meal.slot}) contiene frutta secca, non ammessa per allergie in famiglia.`,
          day: meal.day,
          slot: meal.slot,
        });
      }
    }
  }

  // 5. Ingredienti tassativamente esclusi (restrizioni dietetiche dichiarate).
  const forbiddenIngredients = profiles.flatMap((p) => p.restrictions.map((r) => r.ingredient.toLowerCase()));
  for (const meal of week.meals) {
    for (const forbidden of forbiddenIngredients) {
      const match = meal.recipe.ingredients.find((ing) => ing.name.toLowerCase().includes(forbidden));
      if (match) {
        issues.push({
          code: "forbidden_ingredient",
          message: `"${meal.recipe.name}" (${meal.day} ${meal.slot}) contiene "${match.name}", ingrediente escluso dalla famiglia.`,
          day: meal.day,
          slot: meal.slot,
        });
      }
    }
  }

  // 6. Quantità e unità: ogni ingrediente non "q.b." deve avere quantità e unità valide.
  for (const meal of week.meals) {
    for (const ing of meal.recipe.ingredients) {
      const isFreeform = ing.unit === "q.b.";
      if (!isFreeform && (ing.quantity === null || ing.quantity <= 0 || ing.unit === null)) {
        issues.push({
          code: "invalid_quantity",
          message: `Ingrediente "${ing.name}" in "${meal.recipe.name}" (${meal.day} ${meal.slot}) ha quantità o unità non valide.`,
          day: meal.day,
          slot: meal.slot,
        });
      }
    }
  }

  // 7. Porzioni: devono essere coerenti con una famiglia (>=1).
  for (const meal of week.meals) {
    if (meal.recipe.servings < 1) {
      issues.push({
        code: "invalid_servings",
        message: `Porzioni non valide per "${meal.recipe.name}" (${meal.day} ${meal.slot}).`,
        day: meal.day,
        slot: meal.slot,
      });
    }
  }

  // 8. Duplicazioni: lo stesso piatto non dovrebbe comparire più di una volta
  //    nella stessa settimana (varietà, riduzione della monotonia). La regola
  //    si applica a pranzo/cena: la colazione mediterranea è tipicamente
  //    ricorrente (pane e olio, yogurt e frutta...) e la nostra libreria demo
  //    ha meno ricette da colazione che giorni della settimana, quindi
  //    ripeterle è un comportamento atteso, non un difetto.
  const seenRecipeNames = new Map<string, GeneratedMeal>();
  for (const meal of week.meals) {
    if (meal.slot === "colazione") continue;
    const key = meal.recipe.name.toLowerCase();
    const previous = seenRecipeNames.get(key);
    if (previous) {
      issues.push({
        code: "duplicate_recipe",
        message: `"${meal.recipe.name}" compare più volte nella stessa settimana (${previous.day} ${previous.slot} e ${meal.day} ${meal.slot}).`,
        day: meal.day,
        slot: meal.slot,
      });
    } else {
      seenRecipeNames.set(key, meal);
    }
  }

  return { isValid: issues.length === 0, issues };
}
